### ISSUE TITLE
Invalid dispatcher

### ISSUE THREAD

**Issue by Theblackcat98** [KZDKM/Hyprspace#37] opened 2024-05-03 02:20 UTC
<details>
  <summary>hyprctl systeminfo</summary>
Hyprland, built from branch main at commit 1f6657f037c27b3514d928aa60c3b8c5c05ab8d9  ().
Date: Tue Apr 30 03:42:31 2024
Tag: , commits: 4572

flags: (if any)

System Information:
System name: Linux
Node name: fedora
Release: 6.8.7-200.fc39.x86_64
Version: #1 SMP PREEMPT_DYNAMIC Wed Apr 17 19:35:11 UTC 2024

GPU information:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU106 [GeForce RTX 2060 SUPER] [10de:1f06] (rev a1) (prog-if 00 [VGA controller])

os-release: NAME="Fedora Linux"
VERSION="39 (Workstation Edition)"
ID=fedora
VERSION_ID=39
VERSION_CODENAME=""
PLATFORM_ID="platform:f39"
PRETTY_NAME="Fedora Linux 39 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:39"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f39/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=39
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=39
SUPPORT_END=2024-11-12
VARIANT="Workstation Edition"
VARIANT_ID=workstation

plugins:

</details>

> [!NOTE]
> Notice no plugins being listed at the end, **but** hyprpm sees them.

<details>
  <summary>hyprpm</summary>

- `hyprpm list` && `hyprpm reload` :

```sh
❯ hyprpm list
 → Repository Hyprspace:
  │ Plugin Hyprspace
  └─ enabled: true

❯ hyprpm reload
✔ Ensuring plugin load state
✔ Loaded Hyprspace
✔ Plugin load state ensured
```
</details>

In my `hyprland.conf` I have a simple config to test things out:
> bind = $mainmod ctrl, tab, overview:toggle

Yet I am still getting "Invalid Dispatcher". 

---
P.S. I opened a new issue because #4 was closed and there was someone else with the same problem.

**Comment by KZDKM** [comment] 2024-05-03 13:49
Dupe of #36, `hyprland-git` is not compatible. Roll back to 0.39.1.

**Closed by KZDKM** 2024-05-03 13:49 UTC
