### ISSUE TITLE
Animations are a bit sluggish?

### ISSUE THREAD

**Issue by dmadisetti** [KZDKM/Hyprspace#7] opened 2024-04-11 15:29 UTC
Can we customize this, and if we can, can it be added to the docs?

Takes a good 10 seconds for things to settle for me, which is unlike my other animations

**Comment by KZDKM** [comment] 2024-04-11 15:45
Noted, it is already in the docs, currently the plugin uses the `windows` animation keyword, which should use the same configuration as windows animations. I will try to declare a new animation keyword for the overview panel. Try to decrease the duration of `windows` animation in your hyprland config file.

**Comment by dmadisetti** [comment] 2024-04-11 15:50
What are you using for reference? Here's mine:

`animation=windows,1,5,overshot,slide`

Reasonable at

`animation=windows,1,1,overshot,slide`

but not a fan of normal window animations now

**Comment by KZDKM** [comment] 2024-04-11 15:53
My configuration is the same as the second line. The reason why it uses `windows` animation is I decided it as a placeholder when I was testing the animation implementation during early development. I will try to resolve it now.

**Comment by dmadisetti** [comment] 2024-04-11 15:56
Got you. Changing workspace in overview mode is also much slower than normal change

**Comment by KZDKM** [comment] 2024-04-11 17:24
See this commit: https://github.com/KZDKM/Hyprspace/commit/e3137ae3d89fafade5947cd1e9d2f721ac79d14c

The animation is still based on the `windows` animation but I added a config value for overriding the animation speed. However, I was not able to define a custom animation keyword. 

For switching workspace, the plugin just calls `changeWorkspace` just as workspace dispatcher which you bind to hotkeys would do so I don't know how it would be different with overview open, could you send a video showing how it is slower?

**Comment by dmadisetti** [comment] 2024-04-11 17:34
I will try out the new override at some point- need to get back to work for now

**Comment by dmadisetti** [comment] 2024-04-11 17:36
But my config for reference: https://github.com/dmadisetti/.dots/blob/template/dot/config/hypr/hyprland.conf

**Comment by KZDKM** [comment] 2024-04-11 17:57
Was able to reproduce. This is caused the side effect of overriding the animated positions of windows when drawing workspace windows in overview mode which resets the animation timer of the real position. Wasn't apparent on my config so I did not notice at all. This should be a easy fix.

**Comment by KZDKM** [comment] 2024-04-11 19:10
Fixed with https://github.com/KZDKM/Hyprspace/commit/1a3e22377c9ade3057ff80c9e79930b69adc915f.

Feel free to reopen if issue persists

**Closed** 2024-04-11 19:10 UTC

**Comment by dmadisetti** [comment] 2024-04-11 19:20
Works!
